apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: env-staging
patches:
- target:
    kind: Deployment
    name: guestbook
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
